<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>logo.ico</ApplicationIcon>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.Sqlite" Version="11.0.0-preview.7.26381.103" />
      <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="11.0.0-preview.7.26381.103" />
      <PackageReference Include="Serilog" Version="4.4.1-dev-02443" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\words.txt" />
      <None Update="resources\quotations.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="App.config">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="resources\easytt.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="resources\ziyue.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="resources\asriel.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="resources\capybara.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="resources\alias.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="resources\initialize.sql">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resource\words.txt" />
      <AdditionalFiles Include="resources\words.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </AdditionalFiles>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="CCB">
        <HintPath>..\CCB.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>